version: '3.1'

name: 404state_key_storage
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.flask_app
    restart: always
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - "${FLASK_APP_PORT}"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}"

  database:
    image: postgres
    restart: always
    user: ${POSTGRES_USERNAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}"
    volumes:
      - ${DATABASE_STORAGE_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s