version: '3.1'

name: 404state_key_storage
services:

  key_storage_service:
    build:
      context: .
      dockerfile: Dockerfile.flask_app
    container_name: 404state_key_storage_service
    restart: always
    env_file:
      - ./.env
    environment:
      DOCKER_CONTAINER: '1'
    ports:
      - "5000"