version: '3.1'

name: 404state_key_storage
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.flask_app
    # container_name: 404state_key_storage_service
    restart: always
    env_file:
      - ./.env
    environment:
      DOCKER_CONTAINER: '1'
    ports:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"